// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSSApp.API.Data;

namespace SSSApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200217190313_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("SSSApp.API.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarName")
                        .HasColumnType("TEXT");

                    b.HasKey("CarId");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("SSSApp.API.Models.CarCategory", b =>
                {
                    b.Property<int>("CarCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CarCategoryId");

                    b.ToTable("CarCategory");
                });

            modelBuilder.Entity("SSSApp.API.Models.Conditions", b =>
                {
                    b.Property<int>("ConditionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("ConditionsId");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("SSSApp.API.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverNick")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavouriteNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("DriverId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("SSSApp.API.Models.Rally", b =>
                {
                    b.Property<int>("RallyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RallyName")
                        .HasColumnType("TEXT");

                    b.HasKey("RallyId");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("Rally");
                });

            modelBuilder.Entity("SSSApp.API.Models.RallyEntry", b =>
                {
                    b.Property<int>("RallyEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RallyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("RallyEntryId");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RallyId");

                    b.ToTable("RallyEntry");
                });

            modelBuilder.Entity("SSSApp.API.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DNF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RallyEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("ResultId");

                    b.HasIndex("RallyEntryId");

                    b.HasIndex("StageId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("SSSApp.API.Models.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConditionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RallyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StageId");

                    b.HasIndex("ConditionsId");

                    b.HasIndex("RallyId");

                    b.HasIndex("TrackId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("SSSApp.API.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackName")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackId");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("SSSApp.API.Models.Car", b =>
                {
                    b.HasOne("SSSApp.API.Models.CarCategory", "CarCategory")
                        .WithMany("Cars")
                        .HasForeignKey("CarCategoryId");
                });

            modelBuilder.Entity("SSSApp.API.Models.Rally", b =>
                {
                    b.HasOne("SSSApp.API.Models.CarCategory", "CarCategory")
                        .WithMany("Rallies")
                        .HasForeignKey("CarCategoryId");
                });

            modelBuilder.Entity("SSSApp.API.Models.RallyEntry", b =>
                {
                    b.HasOne("SSSApp.API.Models.Car", "Car")
                        .WithMany("RallyEntries")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSSApp.API.Models.Driver", "Driver")
                        .WithMany("RallyEntries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSSApp.API.Models.Rally", "Rally")
                        .WithMany("RallyEntries")
                        .HasForeignKey("RallyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SSSApp.API.Models.Result", b =>
                {
                    b.HasOne("SSSApp.API.Models.RallyEntry", "RallyEntry")
                        .WithMany("Results")
                        .HasForeignKey("RallyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSSApp.API.Models.Stage", "Stage")
                        .WithMany("Results")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SSSApp.API.Models.Stage", b =>
                {
                    b.HasOne("SSSApp.API.Models.Conditions", "Conditions")
                        .WithMany("Stages")
                        .HasForeignKey("ConditionsId");

                    b.HasOne("SSSApp.API.Models.Rally", "Rally")
                        .WithMany("Stages")
                        .HasForeignKey("RallyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSSApp.API.Models.Track", "Track")
                        .WithMany("Stages")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
